### ISSUE TITLE
Using your code template with kartik ajaxcrud generator

### ISSUE THREAD

**Issue by ingmanuelcaicedo** [hoaaah/yii2-ajaxcrud-bs4#3]
Hi @hoaaah .

I have a little problem, when I try to generate a new crud your extension option doesn't appear between options as you can check here: 

![image](https://user-images.githubusercontent.com/12139208/84450285-4929fa80-ac15-11ea-90be-e47bb5eeb662.png)

How can I change the Code Template option to use your option???

Thank you, so much for your time and for the extension.

**Comment by hoaaah** [comment]
Sorry I can't reproduce your issue. 

1. Use Ajax CRUD Generator options in Gii
2. Could you show me your composer.json?
