### ISSUE TITLE
Modal Title dari H4 ke H5

### ISSUE THREAD

**Issue by ahmadfadlydziljalal** [hoaaah/yii2-ajaxcrud-bs4#6]
Gan, Apa tidak sebaiknya modal title  tagnya pakai H5
ModalRemote.js line 153

```
/**
     * Set modal footer
     * @param {string} title The title of modal
     */
    this.setTitle = function (title) {
        // remove old title
        $(this.header).find('h4.modal-title').remove();
        // add new title
        $(this.header).prepend('<h4 class="modal-title">' + title + '</h4>');
    };

```

Kayak di [https://getbootstrap.com/docs/4.0/components/modal/#modal-components](url)

**Comment by hoaaah** [comment]
Iya betul juga. Nanti kalo sempat diubah om, atau sekalian PR aja om 😀

**Comment by hoaaah** [comment]
Done at https://github.com/hoaaah/yii2-ajaxcrud-bs4/commit/ea1a39c9703658685c835e32f1a856b4c48b0990
